# SPDX-FileCopyrightText: Copyright Â© 2021 snek.at
# SPDX-License-Identifier: EUPL-1.2
#
# Use of this source code is governed by an EUPL-1.2 license that can be found
# in the LICENSE file at https://snek.at/license

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#name
name: Jaen Publish

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_call
  workflow_call:
    # https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
    inputs:
      JAEN_MIGRATION_URL:
        description: Link to the Jaen migrations file.
        # https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype
        type: string
        required: false
      WORKING_DIRECTORY:
        description: Path to working directory in a monorepo.
        # https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype
        type: string
        required: false

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobs
jobs:
  # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_id
  jaen-publish:
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    defaults:
      run:
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsenv
    env:
      JAEN_MIGRATION_URL: ${{ inputs.JAEN_MIGRATION_URL }}

    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:
      # https://github.com/actions/checkout
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith
        with:
          # Relative path under $GITHUB_WORKSPACE to place the repository
          path: "."

      # https://dev.to/mpocock1/how-to-cache-nodemodules-in-github-actions-with-yarn-24eh
      - name: Yarn Cache Directory Path
        id: yarn-cache-dir-path
        # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun
        run: echo "::set-output name=dir::$(yarn cache dir)"

      # https://github.com/marketplace/actions/cache
      - name: Yarn Cache Folder
        uses: actions/cache@v3
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith
        with:
          # https://help.github.com/en/articles/virtual-environments-for-github-actions#default-environment-variables
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      # https://github.com/marketplace/actions/cache
      - name: Yarn Cache Node
        uses: actions/cache@v3
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-pure-lockfile
      - name: Yarn Install
        # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun
        run: yarn install --pure-lockfile

      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsid
      - name: Configure GitHub Authentication ðŸ”§
        # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun
        run: |
          # Git: set identity
          git config user.name "snekmin"
          git config user.email "noreply.snek.at@gmail.com"

          # Git: set remote  
          # https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#http-based-git-access-by-an-installation
          git remote set-url origin "https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"

      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsid
      - name: Update patches.txt with JAEN_MIGRATION_URL
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif
        if: ${{ inputs.JAEN_MIGRATION_URL }}
        # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun
        run: echo "${{ env.JAEN_MIGRATION_URL }}" >> ./jaen-data/patches.txt
